name: Processar Links e Atualizar Cache

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # Executa a cada hora

jobs:
  process-links:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Restaurar Cache seen_links.txt
        uses: actions/cache@v3
        with:
          path: seen_links.txt
          key: seen-links-cache-${{ hashFiles('seen_links.txt') }}
          restore-keys: |
            seen-links-cache-

      - name: Verificar estado do arquivo antes do script
        run: |
          echo "Estado do arquivo antes de executar o script:"
          ls -l seen_links.txt || echo "Arquivo não encontrado"
          sha256sum seen_links.txt || echo "Arquivo não possui checksum"
          cat seen_links.txt || echo "Arquivo vazio ou não existe"

      - name: Executar script Python
        run: python3 pgrp.py

      - name: Verificar estado do arquivo após o script
        run: |
          echo "Estado do arquivo após executar o script:"
          ls -l seen_links.txt || echo "Arquivo não encontrado"
          sha256sum seen_links.txt || echo "Arquivo não possui checksum"
          cat seen_links.txt || echo "Arquivo vazio ou não existe"

      - name: Atualizar Cache seen_links.txt
        uses: actions/cache@v3
        with:
          path: seen_links.txt
          key: seen-links-cache-${{ hashFiles('seen_links.txt') }}
          restore-keys: |
            seen-links-cache-

      - name: Confirmar checksum final
        run: sha256sum seen_links.txt
