name: Send Emails on New Links

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/15 * * * *"

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Certifique-se de que seen_links.txt existe
    - name: Ensure seen_links.txt Exists
      run: |
        if [ ! -f seen_links.txt ]; then
          touch seen_links.txt
        fi

    # Gerar chave de cache dinâmica
    - name: Generate Cache Key
      id: cache-key
      run: |
        checksum=$(sha256sum seen_links.txt | awk '{print $1}')
        echo "key=${{ runner.os }}-seen-links-cache-${checksum}-$(date +%s)" >> $GITHUB_ENV

    # Restaurar cache
    - name: Acquire Cache Lock
      run: |
        while [ -f cache.lock ]; do
          echo "Waiting for cache lock to be released..."
          sleep 5
        done
        touch cache.lock

    - name: Cache seen_links.txt
      uses: actions/cache@v3
      with:
        path: seen_links.txt
        key: ${{ env.key }}
        restore-keys: |
          ${{ runner.os }}-seen-links-cache-

    
    - name: Debug - Show seen_links.txt
  run: |
    if [ -f seen_links.txt ]; then
      cat seen_links.txt
    else
      echo "seen_links.txt does not exist"
    fi


    # Executar script
    - name: Run Script
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
      run: python3 pgrp.py

    # Debug: Verificar o conteúdo do arquivo após
    - name: Debug - Show seen_links.txt After Script
      run: cat seen_links.txt || 

