name: Send Emails on New Links

on:
  # Executa o script em push para a branch principal
  push:
    branches:
      - main
  # Agendado para rodar a cada 15 minutos
  schedule:
    - cron: "*/15 * * * *"
    
jobs:
  process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        - name: Cache seen_links.txt
      uses: actions/cache@v3
      with:
        path: seen_links.txt
        key: ${{ runner.os }}-seen-links-cache-${{ hashFiles('seen_links.txt') }}
        restore-keys: |
          ${{ runner.os }}-seen-links-cache-


    - name: Run Script
      run: python3 pgrp.py

    - name: Save cache if necessary
      run: |
        echo "Saving seen_links.txt to cache."
        cp seen_links.txt ${{ runner.temp }}/seen_links.txt
    
