name: Monitor News

on:
  schedule:
    - cron: "*/5 * * * *"  # Executa a cada 5 minutos
  workflow_dispatch:

jobs:
  monitor-news:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Restaurar o cache para o arquivo seen_links.txt
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            seen_links.txt
          key: monitor-seen-links-${{ runner.os }}
          restore-keys: |
            monitor-seen-links-

      # 3. Instalar dependências
      - name: Instalar dependências
        run: pip install -r requirements.txt

        # Garantir arquivo seen_links.txt
      - name: Garantir arquivo seen_links.txt
        run: |
          if [ ! -f seen_links.txt ]; then
            touch seen_links.txt
          fi

      # Executar o monitor
      - name: Executar monitor
        run: python monitor_pgrp.py

      # 4. Executar o monitor (seu script)
      - name: Executar monitor
        run: python monitor_pgrp.py

      # 5. Salvar o cache atualizado após execução do script
      - name: Save updated cache
        uses: actions/cache@v3
        with:
          path: |
            seen_links.txt
          key: monitor-seen-links-${{ runner.os }}-${{ hashFiles('seen_links.txt') }}
