name: Monitor News

on:
  schedule:
    - cron: '*/15 * * * *'  # Executar a cada 15 minutos

concurrency:
  group: monitor-news  # Evita execuções paralelas
  cancel-in-progress: true  # Cancela a execução anterior se uma nova for disparada

jobs:
  monitor_news:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Fazer o checkout do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # Passo 2: Limpar o cache do Python
      - name: Limpar cache de dependências
        run: |
          rm -rf ~/.cache/pip
          rm -rf /tmp/pip-*

      # Passo 3: Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # Garantir que a versão 3.10 está sendo usada
          cache: 'pip'  # Ativar cache para dependências pip
          clear: true  # Força a instalação sem cache

      # Passo 4: Confirmar versão do Python
      - name: Confirmar versão do Python
        run: |
          python --version  # Confirma a versão do Python
          which python  # Verifica o caminho do Python

      # Passo 5: Instalar dependências
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instalação das dependências a partir do requirements.txt

      # Passo 6: Restaurar o cache do arquivo seen_links.txt
      - name: Restaurar cache
        uses: actions/cache@v3
        with:
          path: seen_links.txt  # Caminho do arquivo de cache
          key: monitor-pgrp-seen-links-${{ runner.os }}  # Chave única para cache
          restore-keys: |
            monitor-pgrp-seen-links-${{ runner.os }}-
            monitor-pgrp-seen-links-  # Chaves adicionais para restaurar caso a principal falhe

      # Passo 7: Executar o monitor
      - name: Executar o monitor
        run: python monitor_pgrp.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

      # Passo 8: Atualizar o cache
      - name: Atualizar cache
        uses: actions/cache@v3
        with:
          path: seen_links.txt  # Caminho do arquivo a ser armazenado no cache
          key: monitor-pgrp-seen-links-${{ runner.os }}  # Usar a mesma chave do cache