# Criar banco de dados SQLite se não existir
- name: Create SQLite Database if Not Exists
  run: |
    python3 -c "
import sqlite3
try:
    conn = sqlite3.connect('seen_links_pgrp.db')
    cursor = conn.cursor()
    cursor.execute('CREATE TABLE IF NOT EXISTS links (link TEXT PRIMARY KEY)')
    conn.commit()
    conn.close()
except sqlite3.DatabaseError as e:
    print(f'Erro ao criar banco de dados: {e}')
    "
