name: Monitor News

on:
  schedule:
    - cron: "*/5 * * * *"  # Executa a cada 5 minutos
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      # 1. Clonar o repositório
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Instalar dependências
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # 4. Garantir que o arquivo seen_links.txt existe
      - name: Ensure seen_links.txt Exists
        run: |
          if [ ! -f seen_links.txt ]; then
            echo "Criando arquivo seen_links.txt vazio"
            touch seen_links.txt
          fi

      # 6. Executar o script
      - name: Run the Script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: |
          python pgrp.py


     

