name: Monitor News

on:
  schedule:
    - cron: '*/15 * * * *'  # Executar a cada 15 minutos

concurrency:
  group: monitor-news  # Evita execuções paralelas
  cancel-in-progress: true  # Cancela a execução anterior se uma nova for disparada

jobs:
  monitor_news:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Fazer o checkout do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # Passo 2: Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'  # Usando um formato de versão explícito
          cache: 'pip'  # Ativar cache para dependências pip

      # Passo 3: Confirmar versão do Python
      - name: Confirmar versão do Python
        run: |
          python --version  # Confirma a versão do Python
          which python  # Verifica o caminho do Python

      # Passo 4: Instalar dependências
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instalação das dependências a partir do requirements.txt

      # Passo 5: Restaurar cache do arquivo seen_links.txt
      - name: Restaurar cache do seen_links.txt
        uses: actions/cache@v3
        with:
          path: seen_links.txt
          key: monitor-seen-links-${{ runner.os }}
          restore-keys: |
            monitor-seen-links-${{ runner.os }}-

      # Passo 6: Verificar conteúdo do arquivo antes de rodar o script
      - name: Verificar conteúdo do seen_links.txt (antes)
        run: |
          if [ -f seen_links.txt ]; then
            echo "Conteúdo de seen_links.txt antes da execução:"
            cat seen_links.txt
          else
            echo "Arquivo seen_links.txt não encontrado."
          fi

      # Passo 7: Executar o script de monitoramento
      - name: Executar o monitor
        run: python monitor_pgrp.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

      # Passo 8: Verificar conteúdo do arquivo após o script
      - name: Verificar conteúdo do seen_links.txt (depois)
        run: |
          if [ -f seen_links.txt ]; then
            echo "Conteúdo de seen_links.txt após a execução:"
            cat seen_links.txt
          else
            echo "Arquivo seen_links.txt não encontrado."
          fi

      # Passo 9: Atualizar o cache
      - name: Atualizar cache do seen_links.txt
        if: success()
        uses: actions/cache@v3
        with:
          path: seen_links.txt
      #    key: monitor-seen-links-${{ runner.os }}

