jobs:
  cache_and_process:
    runs-on: ubuntu-latest

    steps:
      # 1. Restaurar o cache baseado na chave calculada a partir do conteúdo do arquivo
      - name: Restaurar cache
        uses: actions/cache@v3
        id: cache-seen-links
        with:
          path: seen_links.txt
          key: seen-links-cache-${{ hashFiles('seen_links.txt') }}

      # 2. Garantir que o arquivo seen_links.txt existe, caso contrário cria-o
      - name: Garantir que o arquivo seen_links.txt exista
        run: |
          if [ ! -f seen_links.txt ]; then
            touch seen_links.txt
          fi

      # 3. Executar o script Python que vai procurar novos links
      - name: Executar script Python
        run: python3 pgrp.py

      # 4. Verificar se houve mudança e salvar cache com o novo estado do arquivo
      - name: Salvar cache atualizado
        uses: actions/cache@v3
        with:
          path: seen_links.txt
          key: seen-links-cache-${{ hashFiles('seen_links.txt') }}
          restore-keys: |
            seen-links-cache-
