name: Monitor News

on:
  schedule:
    - cron: "*/10 * * * *"  # Executa a cada 10 minutos
  workflow_dispatch:

jobs:
  monitor-news:
    runs-on: ubuntu-latest

    steps:
      # Configura o cache para armazenar o arquivo seen_links.txt
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            seen_links.txt
          key: monitor-seen-links-${{ runner.os }}
          restore-keys: |
            monitor-seen-links-

      # Checkout do código
      - name: Checkout
        uses: actions/checkout@v3

      # Instalar dependências
      - name: Instalar dependências
        run: pip install -r requirements.txt

      # Executar o monitor (seu script)
      - name: Executar monitor
        run: python monitor_pgrp.py

      # Salvar o cache atualizado após execução do script
      - name: Save updated cache
        uses: actions/cache@v3
        with:
          path: |
            seen_links.txt
          key: monitor-seen-links-${{ runner.os }}

