name: Monitor News

on:
  schedule:
    - cron: '*/15 * * * *'  # Executar a cada 15 minutos

concurrency:
  group: monitor-news  # Define um grupo para evitar execuções paralelas
  cancel-in-progress: true  # Cancela o workflow anterior se um novo for disparado

jobs:
  monitor_news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Restaurar cache
        uses: actions/cache@v3
        with:
          path: seen_links.txt
          key: monitor-pgrp-seen-links-${{ runner.os }}-${{ hashFiles('**/*.py') }}  # A chave agora depende de arquivos .py também
          restore-keys: |
            monitor-pgrp-seen-links-${{ runner.os }}-  # Permite uma busca mais ampla por caches anteriores

      - name: Configurar Python
        uses: actions/setup-python@v2  # Usando a versão 2.x, mais estável
        with:
          python-version: 3.10

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Executar o monitor
        run: python monitor_pgrp.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

      - name: Atualizar cache
        uses: actions/cache@v3
        with:
          path: seen_links.txt
          key: monitor-pgrp-seen-links-${{ runner.os }}-${{ hashFiles('**/*.py') }}