name: Monitor News

on:
  schedule:
    - cron: '*/15 * * * *'  # Executar a cada 15 minutos

jobs:
  monitor_news:
    runs-on: ubuntu-latest
    steps:
      # 1. Fazer o checkout do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # 2. Restaurar o cache com os links já vistos
      - name: Restaurar cache
        uses: actions/cache@v3
        with:
          path: seen_links.txt
          key: monitor-pgrp-seen-links

      # 3. Configurar o ambiente Python (usando v2)
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Certifique-se de usar a versão 3.10

      # 4. Instalar dependências
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # 5. Executar o programa
      - name: Executar o monitor
        run: python monitor_pgrp.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

      # 6. Atualizar o cache com os links vistos
      - name: Atualizar cache
        uses: actions/cache@v3
        with:
          path: seen_links.txt
          key: monitor-pgrp-seen-links
