name: Monitor News

on:
  schedule:
    - cron: "*/5 * * * *"  # Executa a cada 5 minutos
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      # 1. Clonar o repositório
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Instalar dependências
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # 4. Garantir que o arquivo seen_links.txt existe
      - name: Ensure seen_links.txt Exists
        run: |
          if [ ! -f seen_links.txt ]; then
            echo "Criando arquivo seen_links.txt vazio"
            touch seen_links.txt
          fi

      # 5. Depurar conteúdo do script
      - name: Debug Script Content
        run: |
          echo "Exibindo o conteúdo do script monitor_pgrp.py:"
          cat monitor_pgrp.py
          echo "Testando importação do script como módulo:"
          python -c "import monitor_pgrp; print('Script carregado com sucesso')"


     

