name: Monitor News

on:
  schedule:
    - cron: "*/5 * * * *"  # Executa a cada 5 minutos
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: List Files in Directory
        run: ls -la
        # Exibe os arquivos presentes no ambiente do GitHub

      - name: Debug Script Content
        run: cat monitor_pgrp.py
        # Mostra o conteúdo do script para identificar problemas

      - name: Check Environment Variables
        run: |
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}"
          echo "TO_EMAIL=${{ secrets.TO_EMAIL }}"
        # Verifica se as variáveis estão configuradas (as senhas são ocultas por padrão)

      - name: Run the Script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: |
          python monitor_pgrp.py
