on:
  schedule:
    - cron: '*/15 * * * *'  # Executar a cada 15 minutos

jobs:
  monitor_news:
    runs-on: ubuntu-latest
    steps:
      # 1. Fazer o checkout do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # 2. Configurar o ambiente Python
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Usando a versão 3.10

      # 3. Instalar dependências
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pytest  # Incluindo pytest

      # 4. Executar os testes com pytest
      - name: Rodar testes
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Executa os testes e para na primeira falha

      # 5. Executar o programa de monitoramento
      - name: Executar o monitor
        run: python monitor_pgrp.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
